import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faPhone,
  faEnvelope,
  faHeart,
  faLanguage,
  faBars,
  faChevronDown,
  faHome,
  faMapMarker,
  faCalendar,
  faUser,
  faMinus,
  faPlus,
  faSearch,
  faAngleDown,
  faStar,
  faWifi,
  faSwimmingPool,
  faCar,
  faConciergeBell,
  faShieldAlt,
  faUsers,
  faCheck,
  faTimes,
  faArrowRight,
  faArrowLeft,
  faQuoteLeft,
  faMapMarkerAlt,
  faPhoneAlt,
  faEnvelopeOpen,
  faCreditCard,
  faBed,
  faMaximize,
  faFilter,
  faSlidersH,
  faBath,
  faCrown,
  faGem,
  faKey,
  faCalendarAlt,
  faSpinner,
} from "@fortawesome/free-solid-svg-icons";
import {
  faHeart as farHeart,
  faCalendar as farCalendar,
  faUser as farUser,
  faStar as farStar,
  faHandshake,
} from "@fortawesome/free-regular-svg-icons";
import {
  faFacebookF,
  faTwitter,
  faInstagram,
  faLinkedinIn,
  faWhatsapp,
} from "@fortawesome/free-brands-svg-icons";

export {
  faPhone,
  faEnvelope,
  faHeart,
  faLanguage,
  faBars,
  faChevronDown,
  faHome,
  faMapMarker,
  faCalendar,
  faUser,
  faMinus,
  faPlus,
  faSearch,
  faAngleDown,
  farHeart,
  farCalendar,
  farUser,
  farStar,
  faStar,
  faWifi,
  faSwimmingPool,
  faCar,
  faConciergeBell,
  faShieldAlt,
  faUsers,
  faCheck,
  faTimes,
  faArrowRight,
  faArrowLeft,
  faQuoteLeft,
  faMapMarkerAlt,
  faPhoneAlt,
  faEnvelopeOpen,
  faHandshake,
  faCreditCard,
  faBed,
  faMaximize,
  faFilter,
  faSlidersH,
  faBath,
  faCrown,
  faGem,
  faKey,
  faCalendarAlt,
  faSpinner,
  faFacebookF,
  faTwitter,
  faInstagram,
  faLinkedinIn,
  faWhatsapp,
};

import { IconDefinition } from "@fortawesome/fontawesome-common-types";

export function Icon({ icon, className = "", ...props }: { icon: IconDefinition; className?: string; [key: string]: unknown }) {
  return <FontAwesomeIcon icon={icon} className={className} {...props} />;
}
